solution/OpticianApp/Pages/Customers/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using OpticianApp.Models;

namespace OpticianApp.Pages.Customers
{
    public class CreateModel : PageModel
    {
        private readonly ApplicationDbContext _context;

        public CreateModel(ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult OnGet()
        {
            return Page();
        }

        [BindProperty]
        public Customer Customer { get; set; } = default!;

        // To protect from overposting attacks, see https://aka.ms/RazorPagesCRUD
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Customer.Add(Customer);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

solution/OpticianApp/Pages/Customers/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using OpticianApp.Models;

namespace OpticianApp.Pages.Customers
{
    public class DeleteModel : PageModel
    {
        private readonly ApplicationDbContext _context;

        public DeleteModel(ApplicationDbContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Customer Customer { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var customer = await _context.Customer.FirstOrDefaultAsync(m => m.ID == id);

            if (customer == null)
            {
                return NotFound();
            }
            else
            {
                Customer = customer;
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var customer = await _context.Customer.FindAsync(id);
            if (customer != null)
            {
                Customer = customer;
                _context.Customer.Remove(Customer);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Index");
        }
    }
}

solution/OpticianApp/Pages/Customers/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using OpticianApp.Models;

namespace OpticianApp.Pages.Customers
{
    public class DetailsModel : PageModel
    {
        private readonly ApplicationDbContext _context;

        public DetailsModel(ApplicationDbContext context)
        {
            _context = context;
        }

        public Customer Customer { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var customer = await _context.Customer.FirstOrDefaultAsync(m => m.ID == id);
            if (customer == null)
            {
                return NotFound();
            }
            else
            {
                Customer = customer;
            }
            return Page();
        }
    }
}

solution/OpticianApp/Pages/Customers/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using OpticianApp.Models;

namespace OpticianApp.Pages.Customers
{
    public class EditModel : PageModel
    {
        private readonly ApplicationDbContext _context;

        public EditModel(ApplicationDbContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Customer Customer { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var customer =  await _context.Customer.FirstOrDefaultAsync(m => m.ID == id);
            if (customer == null)
            {
                return NotFound();
            }
            Customer = customer;
            return Page();
        }

        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Attach(Customer).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!CustomerExists(Customer.ID))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToPage("./Index");
        }

        private bool CustomerExists(int id)
        {
            return _context.Customer.Any(e => e.ID == id);
        }
    }
}

solution/OpticianApp/Pages/Prescriptions/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using OpticianApp.Models;

namespace OpticianApp.Pages.OpticalPrescriptions
{
    public class CreateModel : PageModel
    {
        private readonly ApplicationDbContext _context;

        public CreateModel(ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult OnGet()
        {
        ViewData["CustomerId"] = new SelectList(_context.Customer, "ID", "FullName");
            return Page();
        }

        [BindProperty]
        public OpticalPrescription OpticalPrescription { get; set; } = default!;

        // To protect from overposting attacks, see https://aka.ms/RazorPagesCRUD
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.OpticalPrescription.Add(OpticalPrescription);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

solution/OpticianApp/Pages/Prescriptions/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using OpticianApp.Models;

namespace OpticianApp.Pages.OpticalPrescriptions
{
    public class DeleteModel : PageModel
    {
        private readonly ApplicationDbContext _context;

        public DeleteModel(ApplicationDbContext context)
        {
            _context = context;
        }

        [BindProperty]
        public OpticalPrescription OpticalPrescription { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var opticalprescription = await _context.OpticalPrescription.FirstOrDefaultAsync(m => m.ID == id);

            if (opticalprescription == null)
            {
                return NotFound();
            }
            else
            {
                OpticalPrescription = opticalprescription;
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var opticalprescription = await _context.OpticalPrescription.FindAsync(id);
            if (opticalprescription != null)
            {
                OpticalPrescription = opticalprescription;
                _context.OpticalPrescription.Remove(OpticalPrescription);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Index");
        }
    }
}

solution/OpticianApp/Pages/Prescriptions/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using OpticianApp.Models;

namespace OpticianApp.Pages.OpticalPrescriptions
{
    public class DetailsModel : PageModel
    {
        private readonly ApplicationDbContext _context;

        public DetailsModel(ApplicationDbContext context)
        {
            _context = context;
        }

        public OpticalPrescription OpticalPrescription { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var opticalprescription = await _context.OpticalPrescription.FirstOrDefaultAsync(m => m.ID == id);
            if (opticalprescription == null)
            {
                return NotFound();
            }
            else
            {
                OpticalPrescription = opticalprescription;
            }
            return Page();
        }
    }
}

solution/OpticianApp/Pages/Prescriptions/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using OpticianApp.Models;

namespace OpticianApp.Pages.OpticalPrescriptions
{
    public class EditModel : PageModel
    {
        private readonly ApplicationDbContext _context;

        public EditModel(ApplicationDbContext context)
        {
            _context = context;
        }

        [BindProperty]
        public OpticalPrescription OpticalPrescription { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var opticalprescription =  await _context.OpticalPrescription.FirstOrDefaultAsync(m => m.ID == id);
            if (opticalprescription == null)
            {
                return NotFound();
            }
            OpticalPrescription = opticalprescription;
           ViewData["CustomerId"] = new SelectList(_context.Customer, "ID", "FullName");
            return Page();
        }

        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Attach(OpticalPrescription).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!OpticalPrescriptionExists(OpticalPrescription.ID))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToPage("./Index");
        }

        private bool OpticalPrescriptionExists(int id)
        {
            return _context.OpticalPrescription.Any(e => e.ID == id);
        }
    }
}

solution/OpticianApp/Pages/Prescriptions/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using iTextSharp.text;
using iTextSharp.text.pdf;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using OfficeOpenXml;
using OpticianApp.Models;

namespace OpticianApp.Pages.OpticalPrescriptions
{
    public class IndexModel : PageModel
    {
        private readonly ApplicationDbContext _context;

        public IndexModel(ApplicationDbContext context)
        {
            _context = context;
        }

        public IList<OpticalPrescription> OpticalPrescription { get; set; } = default!;

        public string SearchCustomer { get; set; }
        public DateTime? SearchDate { get; set; }

        public async Task OnGetAsync(string searchCustomer, DateTime? searchDate)
        {
            SearchCustomer = searchCustomer;
            SearchDate = searchDate;

            var prescriptions = _context.OpticalPrescription.Include(p => p.Customer).AsQueryable();

            if (!string.IsNullOrEmpty(SearchCustomer))
            {
                prescriptions = prescriptions.Where(p => p.Customer.Surname.Contains(SearchCustomer));
            }

            if (SearchDate.HasValue)
            {
                prescriptions = prescriptions.Where(p => p.PrescriptionDate.Date == SearchDate.Value.Date);
            }

            OpticalPrescription = await prescriptions.ToListAsync();
        }

        public async Task<IActionResult> OnGetExportToExcel()
        {
            var prescriptions = await _context.OpticalPrescription.Include(x => x.Customer)
            .Select(p => new
            {
                p.PrescriptionDate,
                p.CustomerId,
                CustomerName = p.Customer.FullName,
                p.RightEyeCorrection,
                p.LeftEyeCorrection,
            }).ToListAsync(); // Fetch your data from the database

            ExcelPackage.LicenseContext = LicenseContext.NonCommercial;
            using (var package = new ExcelPackage())
            {

                var worksheet = package.Workbook.Worksheets.Add("Prescriptions");
                worksheet.Cells["A1"].LoadFromCollection(prescriptions, PrintHeaders: true);
                var stream = new MemoryStream();
                package.SaveAs(stream);

                string excelName = $"Prescriptions-{DateTime.Now.ToString("yyyyMMddHHmmssfff")}.xlsx";

                return File(stream.ToArray(), "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", excelName);
            }
        }

        public async Task<IActionResult> OnGetExportToPdf()
        {
            var prescriptions = await _context.OpticalPrescription.Include(x => x.Customer).ToListAsync(); // Fetch your data from the database

            using (MemoryStream stream = new MemoryStream())
            {
                Document pdfDoc = new Document(PageSize.A4.Rotate(), 10f, 10f, 10f, 0f);
                PdfWriter.GetInstance(pdfDoc, stream);
                pdfDoc.Open();

                PdfPTable table = new PdfPTable(6); // Create a table with 6 columns

                // Add table headers
                table.AddCell("Prescription Date");
                table.AddCell("Name");
                table.AddCell("Surname");
                table.AddCell("Address");
                table.AddCell("Left Coorrection");
                table.AddCell("Right Correction");

                foreach (var prescription in prescriptions)
                {
                    // Add customer data to the table
                    table.AddCell(prescription.PrescriptionDate.ToString("dd/MM/yyyy"));
                    table.AddCell(prescription.Customer.Name);
                    table.AddCell(prescription.Customer.Surname);
                    table.AddCell(prescription.Customer.Address);
                    table.AddCell(prescription.LeftEyeCorrection.ToString());
                    table.AddCell(prescription.RightEyeCorrection.ToString());
                }

                pdfDoc.Add(table); // Add the table to the PDF document

                pdfDoc.Close();

                return File(stream.ToArray(), "application/pdf", "Prescriptions.pdf");
            }
        }
    }
}

solution/OpticianApp/Pages/Prescriptions/Create.cshtml
@page
@model OpticianApp.Pages.OpticalPrescriptions.CreateModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>OpticalPrescription</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="OpticalPrescription.CustomerId" class="control-label"></label>
                <select asp-for="OpticalPrescription.CustomerId" class ="form-control" asp-items="ViewBag.CustomerId"></select>
                 <span asp-validation-for="OpticalPrescription.CustomerId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OpticalPrescription.PrescriptionDate" class="control-label"></label>
                <input asp-for="OpticalPrescription.PrescriptionDate" class="form-control" />
                <span asp-validation-for="OpticalPrescription.PrescriptionDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OpticalPrescription.RightEyeCorrection" class="control-label"></label>
                <input asp-for="OpticalPrescription.RightEyeCorrection" class="form-control" />
                <span asp-validation-for="OpticalPrescription.RightEyeCorrection" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OpticalPrescription.LeftEyeCorrection" class="control-label"></label>
                <input asp-for="OpticalPrescription.LeftEyeCorrection" class="form-control" />
                <span asp-validation-for="OpticalPrescription.LeftEyeCorrection" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-page="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

solution/OpticianApp/Pages/Prescriptions/Delete.cshtml
@page
@model OpticianApp.Pages.OpticalPrescriptions.DeleteModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>OpticalPrescription</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.OpticalPrescription.PrescriptionDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.OpticalPrescription.PrescriptionDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.OpticalPrescription.RightEyeCorrection)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.OpticalPrescription.RightEyeCorrection)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.OpticalPrescription.LeftEyeCorrection)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.OpticalPrescription.LeftEyeCorrection)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.OpticalPrescription.Customer)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.OpticalPrescription.Customer.FullName)
        </dd>
    </dl>
    
    <form method="post">
        <input type="hidden" asp-for="OpticalPrescription.ID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-page="./Index">Back to List</a>
    </form>
</div>

solution/OpticianApp/Pages/Prescriptions/Details.cshtml
@page
@model OpticianApp.Pages.OpticalPrescriptions.DetailsModel

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>OpticalPrescription</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.OpticalPrescription.PrescriptionDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.OpticalPrescription.PrescriptionDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.OpticalPrescription.RightEyeCorrection)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.OpticalPrescription.RightEyeCorrection)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.OpticalPrescription.LeftEyeCorrection)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.OpticalPrescription.LeftEyeCorrection)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.OpticalPrescription.Customer)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.OpticalPrescription.Customer.ID)
        </dd>
    </dl>
</div>
<div>
    <a asp-page="./Edit" asp-route-id="@Model.OpticalPrescription.ID">Edit</a> |
    <a asp-page="./Index">Back to List</a>
</div>

solution/OpticianApp/Pages/Prescriptions/Edit.cshtml
@page
@model OpticianApp.Pages.OpticalPrescriptions.EditModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>OpticalPrescription</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="OpticalPrescription.ID" />
            <div class="form-group">
                <label asp-for="OpticalPrescription.CustomerId" class="control-label"></label>
                <select asp-for="OpticalPrescription.CustomerId" class="form-control" asp-items="ViewBag.CustomerId"></select>
                <span asp-validation-for="OpticalPrescription.CustomerId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OpticalPrescription.PrescriptionDate" class="control-label"></label>
                <input asp-for="OpticalPrescription.PrescriptionDate" class="form-control" />
                <span asp-validation-for="OpticalPrescription.PrescriptionDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OpticalPrescription.RightEyeCorrection" class="control-label"></label>
                <input asp-for="OpticalPrescription.RightEyeCorrection" class="form-control" />
                <span asp-validation-for="OpticalPrescription.RightEyeCorrection" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OpticalPrescription.LeftEyeCorrection" class="control-label"></label>
                <input asp-for="OpticalPrescription.LeftEyeCorrection" class="form-control" />
                <span asp-validation-for="OpticalPrescription.LeftEyeCorrection" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-page="./Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

solution/OpticianApp/Pages/Prescriptions/Index.cshtml
@page
@model OpticianApp.Pages.OpticalPrescriptions.IndexModel

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-page="Create">Create New</a>
    <a asp-page-handler="ExportToPdf">Export to PDF</a>
    <a asp-page-handler="ExportToExcel">Export to Excel</a>
</p>
<form asp-page="Index" method="get">
    <p>
        Customer: <input type="text" name="SearchCustomer" value="@Model.SearchCustomer">
        Date: <input type="date" name="SearchDate" value="@Model.SearchDate">
        <input type="submit" value="Search" />
    </p>
</form>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.OpticalPrescription[0].PrescriptionDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.OpticalPrescription[0].RightEyeCorrection)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.OpticalPrescription[0].LeftEyeCorrection)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.OpticalPrescription[0].Customer)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.OpticalPrescription)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.PrescriptionDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.RightEyeCorrection)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LeftEyeCorrection)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Customer.FullName)
                </td>
                <td>
                    <a asp-page="./Edit" asp-route-id="@item.ID">Edit</a> |
                    <a asp-page="./Details" asp-route-id="@item.ID">Details</a> |
                    <a asp-page="./Delete" asp-route-id="@item.ID">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>